AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/smoke_test.rb'
    - 'vendor/**/*'
    - 'bin/*'
  RunRailsCops: true
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/RaiseArgs:
  Enabled: false
Style/GlobalVars:
  Enabled: false
